<?php

use DenielWorld\TechMinePM\Main;
use pocketmine\block\BlockToolType;
use pocketmine\block\Solid;
use pocketmine\item\Item;
use pocketmine\block\Block;
use pocketmine\level\Explosion;
use pocketmine\level\particle\SmokeParticle;
use pocketmine\math\Vector3;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\nbt\tag\IntTag;
use pocketmine\nbt\tag\StringTag;
use pocketmine\Player;
use pocketmine\tile\Tile;

class CoalGenerator extends Solid {

    protected $id = self::COMMAND_BLOCK;

    private $plugin;

    public function __construct(Main $plugin, int $meta = 1)
    {
        parent::__construct(self::COMMAND_BLOCK, 1);
        $this->meta = $meta;
        $this->plugin = $plugin;
    }

    public function getName(): string
    {
        return "Coal Generator";
    }

    public function getHardness(): float
    {
        return 4;
    }

    public function getBreakTime(Item $item): float
    {
        return parent::getBreakTime($item); // TODO: Hope this works
    }

    public function getToolType(): int
    {
        return BlockToolType::TYPE_PICKAXE;
    }

    public function getSide(int $side, int $step = 1)
    {
        return parent::getSide($side, $step); // TODO: Change the autogenerated stub
    }

    public function getDrops(Item $item): array
    {
        return [new Item(self::COMMAND_BLOCK, 1)];
    }

    public function place(Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, Player $player = null): bool
    {
        $manager = $this->plugin->getBlockManager();
        $manager->setBlockAt($blockReplace->x, $blockReplace->y, $blockReplace->z, $blockReplace->level, $blockReplace, 1);
        $nbt = new CompoundTag("", [
            new StringTag(Tile::TAG_ID, "Coal Generator"),
            new IntTag(Tile::TAG_X, (int)$this->x),
            new IntTag(Tile::TAG_Y, (int)$this->y),
            new IntTag(Tile::TAG_Z, (int)$this->z),
        ]);
        $nbt->setInt("energy", 0);
        $nbt->setInt("coal", 0);
        new \DenielWorld\TechMinePM\tile\CoalGenerator($player->getLevel(), $nbt);
        return $this->getLevel()->setBlock($this, $this, true, true);
    }

    public function onActivate(Item $item, Player $player = null): bool
    {
        $tile = $player->getLevel()->getTile($this->asVector3());
        if($tile instanceof \DenielWorld\TechMinePM\tile\CoalGenerator){
            $player->addWindow($tile->getInventory());
            return true;
        }
        return false;
    }

    public function getXpDropAmount(): int
    {
        return 0;
    }

    public function getXpDropForTool(Item $item): int
    {
        return 0;
    }

    public function getBlastResistance(): float
    {
        return $this->getHardness() * 5;
    }

    public function isFlammable(): bool
    {
        return true;
    }

    public function getFlammability(): int
    {
        return 7;
    }

    public function getFlameEncouragement(): int
    {
        return 7;
    }

    public function onIncinerate(): void
    {
        $boom = new Explosion($this->asPosition(), 3);
        $smoke = new SmokeParticle($this->asVector3(), 3);
        $boom->explodeA();
        $boom->explodeB();
        $this->getLevel()->addParticle($smoke);
        //todo release CO2 in large quantity (when added)
    }

    public function isBreakable(Item $item): bool
    {
        return true;
    }
}