<?php

use DenielWorld\TechMinePM\Main;
use pocketmine\block\BlockToolType;
use pocketmine\block\Solid;
use pocketmine\item\Item;
use pocketmine\block\Block;
use pocketmine\level\Explosion;
use pocketmine\level\particle\SmokeParticle;
use pocketmine\math\Vector3;
use pocketmine\Player;

class CoalGenerator extends Solid {

    protected $id = self::COMMAND_BLOCK;

    private $plugin;

    public function __construct(Main $plugin, int $meta = 1)
    {
        parent::__construct(self::COMMAND_BLOCK, 1);
        $this->meta = $meta;
        $this->plugin = $plugin;
    }

    public function getHardness(): float
    {
        return 4;
    }

    public function getToolType(): int
    {
        return BlockToolType::TYPE_PICKAXE;
    }

    public function getSide(int $side, int $step = 1)
    {
        return parent::getSide($side, $step); // TODO: Change the autogenerated stub
    }

    public function getDrops(Item $item): array
    {
        return [new Item(self::COMMAND_BLOCK, 1)];
    }

    public function place(Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, Player $player = null): bool
    {
        $manager = $this->plugin->getBlockManager();
        $manager->setBlockAt($blockReplace->x, $blockReplace->y, $blockReplace->z, $blockReplace->level, $blockReplace, 1);
        return $this->getLevel()->setBlock($this, $this, true, true);
    }

    public function getXpDropAmount(): int
    {
        return 0;
    }

    public function getXpDropForTool(Item $item): int
    {
        return 0;
    }

    public function getBlastResistance(): float
    {
        return $this->getHardness() * 5;
    }

    public function isFlammable(): bool
    {
        return true;
    }

    public function getFlammability(): int
    {
        return 7;
    }

    public function getFlameEncouragement(): int
    {
        return 7;
    }

    public function onIncinerate(): void
    {
        $boom = new Explosion($this->asPosition(), 3);
        $smoke = new SmokeParticle($this->asVector3(), 3);
        $boom->explodeA();
        $boom->explodeB();
        $this->getLevel()->addParticle($smoke);
        //todo release CO2 in large quantity (when added)
    }

    public function isBreakable(Item $item): bool
    {
        return true;
    }
}